src/Entity/Figures.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Vich\UploaderBundle\Entity\File as EmbeddedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FiguresRepository")
 * @UniqueEntity("name")
 * @Vich\Uploadable()
 */
class Figures
{
	/**
	 * @ORM\Id()
	 * @ORM\GeneratedValue()
	 * @ORM\Column(type="integer")
	 */
	private $id;

	/**
	 * @ORM\Column(type="string", length=255)
	 */
	private $name;

	/**
	 * @ORM\Column(type="text")
	 */
	private $description;

	/**
	 * @ORM\Column(type="datetime")
	 */
	private $created_at;

	/**
	 * @ORM\Column(type="datetime")
	 */
	private $updated_at;

	/**
	 * @Groups("comments")
	 * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="figure")
	 */
	private $comments;

	/**
	 * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="figures")
	 */
	private $categories;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="figures", orphanRemoval=true, cascade={"persist"})
	 */
	private $pictures;

	/**
	 * @Assert\All({
	 *   @Assert\Image(mimeTypes={"image/png", "image/jpeg"})
	 * })
	 */
	private $pictureFiles;

	/**
	 * @ORM\Column(type="string", length=255, nullable=true)
	 */
	private $main_image;

	/**
	 * @var File|null
	 * @Assert\Image(
	 *     mimeTypes={"image/png", "image/jpeg"}
	 * )
	 * @Vich\UploadableField(mapping="figure_main_image", fileNameProperty="main_image")
	 */
	private $mainImgFile;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\Video", mappedBy="figure", cascade={"remove"})
	 */
	private $videos;

	public function __construct()
	{
		$this->comments = new ArrayCollection();
		$this->categories = new ArrayCollection();
		$this->pictures = new ArrayCollection();
		$this->videos = new ArrayCollection();
	}

	public function __toString()
	{
		return $this->name;
	}

	public function getId(): ?int
	{
		return $this->id;
	}

	public function getName(): ?string
	{
		return $this->name;
	}

	public function setName(string $name): self
	{
		$this->name = $name;

		return $this;
	}

	public function getSlug(): string
	{
		return (new Slugify())->slugify($this->name);
	}

	public function getDescription(): ?string
	{
		return $this->description;
	}

	public function setDescription(string $description): self
	{
		$this->description = $description;

		return $this;
	}

	public function getCreatedAt(): ?\DateTimeInterface
	{
		return $this->created_at;
	}

	public function setCreatedAt(\DateTimeInterface $created_at): self
	{
		$this->created_at = $created_at;

		return $this;
	}

	public function getUpdatedAt(): ?\DateTimeInterface
	{
		return $this->updated_at;
	}

	public function setUpdatedAt(\DateTimeInterface $updated_at): self
	{
		$this->updated_at = $updated_at;

		return $this;
	}

	public function dateIsSame()
	{
		return $this->created_at == $this->updated_at;
	}

	/**
	 * @return Collection|Comment[]
	 */
	public function getComments(): Collection
	{
		return $this->comments;
	}

	public function addComment(Comment $comment): self
	{
		if (!$this->comments->contains($comment)) {
			$this->comments[] = $comment;
			$comment->setFigure($this);
		}

		return $this;
	}

	public function removeComment(Comment $comment): self
	{
		if ($this->comments->contains($comment)) {
			$this->comments->removeElement($comment);
			// set the owning side to null (unless already changed)
			if ($comment->getFigure() === $this) {
				$comment->setFigure(null);
			}
		}

		return $this;
	}

	/**
	 * @return Collection|Category[]
	 */
	public function getCategories(): Collection
	{
		return $this->categories;
	}

	public function addCategory(Category $category): self
	{
		if (!$this->categories->contains($category)) {
			$this->categories[] = $category;
			$category->addFigure($this);
		}

		return $this;
	}

	public function removeCategory(Category $category): self
	{
		if ($this->categories->contains($category)) {
			$this->categories->removeElement($category);
			$category->removeFigure($this);
		}

		return $this;
	}

	/**
	 * @return Collection|Picture[]
	 */
	public function getPictures(): Collection
	{
		return $this->pictures;
	}

	public function getPicture(): ?Picture
	{
		if ($this->pictures->isEmpty()) {
			return null;
		}
		return $this->pictures->first();
	}

	public function addPicture(Picture $picture): self
	{
		if (!$this->pictures->contains($picture)) {
			$this->pictures[] = $picture;
			$picture->setFigures($this);
		}

		return $this;
	}

	public function removePicture(Picture $picture): self
	{
		if ($this->pictures->contains($picture)) {
			$this->pictures->removeElement($picture);
			// set the owning side to null (unless already changed)
			if ($picture->getFigures() === $this) {
				$picture->setFigures(null);
			}
		}

		return $this;
	}

	/**
	 * @return mixed
	 */
	public function getPictureFiles()
	{
		return $this->pictureFiles;
	}

	/**
	 * @param mixed $pictureFiles
	 * @return Figures
	 */
	public function setPictureFiles($pictureFiles): self
	{
		foreach ($pictureFiles as $pictureFile) {
			$picture = new Picture();
			$picture->setImageFile($pictureFile);
			$this->addPicture($picture);
		}
		$this->pictureFiles = $pictureFiles;
		return $this;
	}

	public function getMainImage(): ?string
	{
		return $this->main_image;
	}

	public function setMainImage(?string $main_image): self
	{
		$this->main_image = $main_image;

		return $this;
	}

	/**
	 * Get mimeTypes={"image/png", "image/jpeg"}
	 *
	 * @return  File|null
	 */
	public function getMainImgFile()
	{
		return $this->mainImgFile;
	}

	/**
	 * Set mimeTypes={"image/png", "image/jpeg"}
	 *
	 * @param  File|null  $mainImgFile  mimeTypes={"image/png", "image/jpeg"}
	 *
	 * @return  self
	 */
	public function setMainImgFile($mainImgFile)
	{
		$this->mainImgFile = $mainImgFile;

		return $this;
	}

	/**
	 * @return Collection|Video[]
	 */
	public function getVideos(): Collection
	{
		return $this->videos;
	}

	public function addVideo(Video $video): self
	{
		if (!$this->videos->contains($video)) {
			$this->videos[] = $video;
			$video->setFigure($this);
		}

		return $this;
	}

	public function removeVideo(Video $video): self
	{
		if ($this->videos->contains($video)) {
			$this->videos->removeElement($video);
			// set the owning side to null (unless already changed)
			if ($video->getFigure() === $this) {
				$video->setFigure(null);
			}
		}

		return $this;
	}
}

src/Form/FigureType.php
<?php

namespace App\Form;

use App\Entity\Figures;
use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class FigureType extends AbstractType
{
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$builder
			->add('mainImgFile', FileType::class, [
				'required' => false,
				'multiple' => false,
			])
			->add('pictureFiles', FileType::class, [
				'required' => false,
				'label' => 'Photos supplémentaires',
				'multiple' => true
			])
			->add('name')
			->add('categories', EntityType::class, [
				'class' => Category::class,
				'choice_label' => 'name',
				'multiple' => true,
				'required' => false,
			])
			->add('description');
	}

	public function configureOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults([
			'data_class' => Figures::class,
			'translation_domain' => 'forms'
		]);
	}
}

src/Controller/FigureController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Figures;
use App\Form\CommentType;
use App\Repository\CommentRepository;
use App\Repository\FiguresRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class FigureController extends AbstractController
{
	/**
	 * @var CommentRepository
	 */
	private $commentRepository;

	/**
	 * @var FiguresRepository
	 */
	private $figuresRepository;

	/**
	 * @var ObjectManager
	 */
	private $em;

	public function __construct(CommentRepository $commentRepository, FiguresRepository $figuresRepository, ObjectManager $em)
	{
		$this->commentRepository = $commentRepository;
		$this->figuresRepository = $figuresRepository;
		$this->em = $em;
	}

	/**
	 * @Route("/figure/{slug}-{id}", name="figure.show", requirements={"slug": "[a-z0-9\-]*"})
	 * @return Response
	 * @param figure $figure
	 */
	public function show(Figures $figure, string $slug, Request $request): Response
	{
		$user = $this->getUser();
		$comments = $this->commentRepository->findItems(1, $figure->getId());
		$nbGroups = round($this->commentRepository->countAll($figure->getId()) / 10);

		if ($user) {
			$comment = new Comment();
			$form = $this->createForm(CommentType::class, $comment);
			$form->handleRequest($request);

			if ($form->isSubmitted() && $form->isValid()) {
				$date = new \DateTime();
				$comment->setCreatedAt($date);
				$comment->setFigure($figure);
				$comment->setUser($user);

				$this->em->persist($comment);
				$this->em->flush();
				$this->addFlash('success', 'Le commentaire a bien été rajouté');

				return $this->redirectToRoute('figure.show', [
					'id' => $figure->getId(),
					'slug' => $figure->getSlug(),
					'nbGroups' => $nbGroups,
				], 301);
			}
		}


		if ($slug === $figure->getSlug()) {
			return $this->render('figure/show.html.twig', [
				'figure' => $figure,
				'id' => $figure->getId(),
				'slug' => $figure->getSlug(),
				'current_menu' => 'figure.show',
				'date_is_same' => $figure->dateIsSame(),
				'comments' => $comments,
				'form' => isset($form) && $form ? $form->createView() : false,
				'nbGroups' => $nbGroups,
			]);
		}

		return $this->render('figure/show.html.twig', [
			'id' => $figure->getId(),
			'slug' => $figure->getSlug(),
			'nbGroups' => $nbGroups,
		]);
	}

	/**
	 * @Route("/figure/{id}/commentaire/index/{index}", name="figure.commentaire.index")
	 *
	 * @return Response
	 */
	public function ajaxLoadItems(Request $request)
	{
		$params = $request->attributes->get('_route_params');
		$index = (int) $params['index'];
		$idFigure = $params['id'];
		$nbGroups = round($this->commentRepository->countAll($idFigure) / 10);

		if (is_int($index) && $index > 1) {
			$moreComments = (array) $this->commentRepository->findMoreItems($index, $idFigure);
			$htmlData = [];

			if ($moreComments) {
				foreach ($moreComments as $comment) {
					$comment = $this->getDoctrine()
						->getRepository(Comment::class)
						->find($comment['id']);

					array_push(
						$htmlData,
						$this->renderView('./comment.html.twig', [
							'comment' => $comment,
							'nbGroups' => $nbGroups,
						])
					);
				}
			}

			return new JsonResponse([
				'html' => $htmlData,
			], 200);
		}

		return new JsonResponse(['error' => 'Une erreur est survenue'], 400);
	}
}

templates/figure/_figure.html.twig
<a href="{{ path('figure.show', { id: figure.id, slug: figure.slug }) }}" class="card mt-4 figure">
	{% if figure.pictures|length > 0 and (figure.mainImage is null or figure.mainImage is empty) %}
		{% if 'image-' in figure.pictures|last.filename %}
			{% set mainImage = asset('build/images/' ~ figure.pictures|last.filename) %}
		{% else %}
			{% set mainImage = vich_uploader_asset(figure.pictures|last, 'imageFile') %}
		{% endif %}
	{% elseif figure.mainImage is not null %}
		{% if 'image-' in figure.mainImage %}
			{% set mainImage = asset('build/images/' ~ figure.mainImage) %}
		{% else %}
			{% set mainImage = vich_uploader_asset(figure, 'mainImgFile') | imagine_filter('thumb') %}
		{% endif %}
	{% elseif figure.mainImage is null and 'image-' in figure.pictures|last.filename %}
		{% set mainImage = asset('build/images/' ~ figure.pictures|last.filename) %}
	{% endif %}

	<div class="card-img-top" style="background-image: url({{ mainImage is defined and mainImage is not empty ? mainImage : asset('build/images/empty.jpg') }})"></div>
	<div class="card-body">
		<h5 class="card-title">
			<p>
				{{ figure.name }}
			</p>
		</h5>
		{% if app.user %}
			<div class="actions">
				<form action="{{ path('admin.figure.edit', {id: figure.id}) }}" style="display: inline-block">
					<button class="btn btn-link edit">
						<i class="fa fa-pencil" aria-hidden="true"></i>
					</button>
				</form>
				<form method="post" action="{{ path('admin.figure.delete', {id: figure.id}) }}" style="display: inline-block" onsubmit="return confirm('Vous êtes sur le point de supprimer une figure. Êtes vous vraiment sûr ?')">
					<input type="hidden" name="_method" value="DELETE">
					<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ figure.id) }}">
					<button class="btn btn-link delete">
						<i class="fa fa-trash" aria-hidden="true"></i>
					</button>
				</form>
			</div>
		{% endif %}

	</div>
</a>

templates/figure/show.html.twig
{% extends "base.html.twig" %}

{% block title figure.name ~ ' | SnowTricks' %}
{% block h1 figure.name %}
{% block subtitle figure.description %}

{% block body %}

	<div class="figure-container col text-center container">
		{% if app.user %}
			<div class="actions">
				<a class="edit" href="{{ path('admin.figure.edit', {id: figure.id}) }}">
					<i class="fa fa-pencil" aria-hidden="true"></i>
				</a>
				<form method="post" action="{{ path('admin.figure.delete', {id: figure.id}) }}" style="display: inline-block" onsubmit="return confirm('Vous êtes sur le point de supprimer une figure. Êtes vous vraiment sûr ?')">
					<input type="hidden" name="_method" value="DELETE">
					<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ figure.id) }}">
					<button class="btn btn-link delete">
						<i class="fa fa-trash" aria-hidden="true"></i>
					</button>
				</form>
			</div>
		{% endif %}

		{% if figure.pictures|length > 0 and (figure.mainImage is null or figure.mainImage is empty) %}
			{% if 'image-' in figure.pictures|last.filename %}
				{% set mainImage = asset('build/images/' ~ figure.pictures|last.filename) %}
			{% else %}
				{% set mainImage = vich_uploader_asset(figure.pictures|last, 'imageFile') | imagine_filter('large') %}
			{% endif %}
		{% elseif (figure.mainImage is not null) %}
			{% if 'image-' in figure.mainImage %}
				{% set mainImage = asset('build/images/' ~ figure.mainImage) %}
			{% else %}
				{% set mainImage = vich_uploader_asset(figure, 'mainImgFile') | imagine_filter('large') %}
			{% endif %}
		{% elseif 'image-' in figure.pictures|last.filename %}
			{% set mainImage = asset('build/images/' ~ figure.pictures|last.filename) %}
		{% endif %}

		<div class="image" style="background-image: url({{ mainImage is defined and mainImage is not empty ? mainImage : asset('build/images/empty.jpg') }});">
			<h1>
				{{figure.name}}
			</h1>
		</div>
		<a class="btn btn-primary media-mobile" data-toggle="collapse" href="#mediaCollapse" role="button" aria-expanded="false" aria-controls="mediaCollapse">
			Voir les médias
		</a>
		<div class="collapse" id="mediaCollapse">
			<div class="medias">
				<div class="photos">
					{% for picture in figure.pictures %}
						{% if 'image-' in picture.filename %}
							{% set url = asset('build/images/' ~ picture.filename) %}
						{% else %}
							{% set url = vich_uploader_asset(picture, 'imageFile') | imagine_filter('thumb') %}
						{% endif %}
						<div class="photo miniature" style="background-image: url({{ url }})"></div>
					{% endfor %}
				</div>
				<div class="videos">
					{% for video in figure.videos %}
						<div class="miniature">
							{{ video.url|raw }}
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
		<div class="row text">
			<div class="col text-left">
				{{ figure.description }}
			</div>
		</div>
		<div class="btn-toolbar infos justify-content-center" role="toolbar" aria-label="Toolbar with button groups">
			<div class="btn-group mr-2" role="group">
				<a href="#" class="btn btn-info">
					Créée le
					{{ figure.createdAt|date("d/m/Y") }}
				</a>
			</div>
			{% for category in figure.categories %}
				<div class="btn-group mr-2" role="group">
					<a href="#" class="btn btn-info">
						{{category.name}}
					</a>
				</div>
			{% endfor %}
			{% if not date_is_same %}
				<div class="btn-group" role="group">
					<a href="#" class="btn btn-info">
						Modifiée le
						{{ figure.updatedAt|date("d/m/Y") }}
					</a>
				</div>
			{% endif %}
		</div>
		<div class="comments-container {{ comments|length == 0 ? 'hide' : ''}}">
			<h2>
				Commentaires
			</h2>

			{% include "flash.html.twig" %}

			{% if app.user and form is defined %}


				{{ form_start(form) }}

				<div class="row">
					<div class="col">
						{{ form_row(form.content) }}
					</div>
				</div>

				<button class="btn btn-primary">
					{{ button|default('Ajouter un commentaire') }}
				</button>

				{{ form_end(form) }}

			{% endif %}

			{% if comments is defined %}
				<div class="comments">
					<input type="hidden" value="{{ nbGroups }}" id="limit">
					{% for comment in comments %}
						{% include "comment.html.twig" with {'comment': comment} %}
					{% endfor %}
				</div>
			{% endif %}
			<a href="{{ path("figure.commentaire.index", { id: figure.id, index: 2 }) }}" class="btn btn-lg btn-primary mt-4 load-more">
				Charger plus de commentaires
				<div class="spinner-border" role="status">
					<span class="sr-only">Loading...</span>
				</div>
			</a>
		</div>
	</div>

{% endblock body %}